### ISSUE TITLE
Staking: Test Staking and Delegation on Testnet

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#11]
Need to deploy `contracts/FlowIDTableStaking` on testnet and test with automated tests as well as manual tests.

**Comment by robmyers** [comment]
There seems to be some work on this here?

https://github.com/onflow/flow-core-contracts/blob/kan/test-on-testnet/lib/go/test/

**Comment by joshuahannan** [comment]
yeah, those are the manual tests, but theoretically we also need to test on testnet. That is what the #staking-testing channel is for in discord. It was supposed to be this week, but I got sidetracked this week with the locked tokens contract so I had to postpone it unfortunately. 

I had made this document for community members to sign up for testnet testing: https://docs.google.com/spreadsheets/d/1FsllCA7tZdO93riUqaqQHmFvh256Bup6ZS09GUSLNkQ/edit#gid=0

and I have a local branch of this repo with instructions for everyone. Do you think you might be able to help with the test plan @robmyers ?

**Comment by robmyers** [comment]
Absolutely. Can I get access to that branch?

**Comment by laynelafrance** [comment]
Issues with staking contract during nov 24 testnet spork - determining if these are isolated to testnet spork changes cc @Kay-Zee

**Comment by joshuahannan** [comment]
What happened with the staking contract?
