### ISSUE TITLE
LockedTokensDeposited not emitted

### ISSUE THREAD

**Issue by robmyers** [onflow/flow-core-contracts#121]
LockedTokensDeposited is declared in LockedTokens but not emitted in the code. Is it meant to be emitted in deposit() or somewhere?

https://github.com/onflow/flow-core-contracts/blob/master/contracts/LockedTokens.cdc#L44

https://github.com/onflow/flow-core-contracts/blob/master/contracts/LockedTokens.cdc#L304

**Comment by joshuahannan** [comment]
I defined it because I thought I needed it, but locked tokens are just deposited through the normal fungible token receiver, so it wasn't actually needed. I just forgot to remove it. 🤷
