### ISSUE TITLE
Amounts for staking

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-core-contracts#13]
A balance of 10K Flow looks like this:  `balance: 1000000000000`

Just checking that the minimums are right here:
https://github.com/onflow/flow-core-contracts/blob/35f281b3515ed495a72b8288f1473e4f1fb9cf46/contracts/FlowIDTableStaking.cdc#L1047

**Comment by joshuahannan** [comment]
@cybercent Are you sure you aren't getting this mixed up with how ETH is represented in Solidity? In Cadence we use `UFix64` to represent Flow tokens, so we can have 10k FLOW represented as `10000.0`.

**Comment by joshuahannan** [comment]
The number still has precision up to 8 decimal places, but it is only represented as an integer under the hood. We can represent it as a decimal number in Cadence.

**Comment by cybercent** [comment]
@joshuahannan thanks for the explanation. 
The confusion came from when I queried an account's balance via gRPC.
I see the amount like this: `1000000000000` not like this `10000.0`, probably because there is no UFix64 in Go. 

I opened the issue just to check that there was no mistake there. Good to know the amounts are correct.

**Comment by psiemens** [comment]
@cybercent Was just going to ask if that number is reported by the Go SDK. Are you calling `GetAccount`? I think we can update the Go SDK to use `cadence.UFix64` to represent the `balance` field
