### ISSUE TITLE
Check that node operator public keys are valid

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-core-contracts#141]
## Context

When a node operator registers to stake, we should validate their public keys to ensure they are well-formed, using the updated `Crypto` contract in Cadence (https://github.com/onflow/cadence/issues/582). 

## Definition of Done

* Staking key (BLS) and networking key (ECDSA) inputs are validated during staking registration
* A staking request with any invalid keys is rejected
* Public key fields are stored as the appropriate `Crypto.PublicKey` type

**Comment by joshuahannan** [comment]
@jordanschalm @tarakby This seems like this is going to require a lot more planning and estimating, especially if we want to perform this validation for the staking contract as well as the dkg contract. It also is a significant change to the smart contracts. We definitely don't have time to implement this before the quantstamp review starts, so it makes me nervous to have them audit a contract that still isn't finished.

**Comment by jordanschalm** [comment]
This probably applies to https://github.com/onflow/flow-core-contracts/issues/181 as well. cc @franklywatson 

I'm not sure what the process is like with the auditors lately but ideally we can submit multiple versions over time as we make changes to the contracts. Most of these contracts will be seeing much more significant changes than those in these 2 tickets, for upcoming features like BFT and slashing, which will need to be audited as separate versions as well. 

To me these key validation issues seem like exactly the sort of issues that an audit would bring up to address, and a follow-up audit on an updated version would confirm (we just know about these issues already!)

**Comment by tarakby** [comment]
I agree these kind of missing checks are what an audit would be looking at and adding to the finding report.

I'm not aware of the audit deadlines, the security constraint is to have these checks integrated to the staking and dkg contracts before we stop manual sporks and start the epoch feature. 

Regarding the task itself, here is the more explicit [Cadence API](https://github.com/onflow/cadence/blob/tarak/crypto-doc/docs/language/crypto.mdx#publickey) to validate public keys. It's finalized on Cadence but still wip on the FVM.

**Comment by joshuahannan** [comment]
ok. yeah we can probably just move forward with the audit then and just do some re-audits later when we have more features.
