### ISSUE TITLE
Accept FirstView, FinalView as arguments to resetEpoch

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-core-contracts#180]
## Context

When resetting an epoch, it is critical that the smart contract epoch metadata remains in sync (exactly) with the protocol state epoch metadata. Since the protocol state epoch metadata is generated first, then injected to the smart contract with the `resetEpoch` function, the `resetEpoch` function must accept as input all metadata fields which must be synchronized. 

## Definition of Done

* Accept 2 additional inputs to `resetEpoch` - `startView` and `endView`
* Change computation of `stakingEndView` to use injected `startView` rather than current block 
Change  to use startView that is injected
* Enforce sanity check for epoch length input, given the configured DKG phase length and staking auction length, similar to the [checks in place for changing configuration](https://github.com/onflow/flow-core-contracts/blob/feature/epochs/contracts/epochs/FlowEpoch.cdc#L275)

**Comment by joshuahannan** [comment]
We shouldn't provide `endView` as an input, right? because we can just calculate that from the `startView` and the epoch length in views, or just leave it as the same end view as before?

**Comment by jordanschalm** [comment]
If the `EndView` generated by the bootstrapping process doesn't exactly match the smart contract's state after the `resetEpoch` call, the next epoch transition will fail. In general it's really important to keep all these values synchronized between protocol state and smart contract state. 

So I think we should still accept `endView as input to be able to ensure that consistency, even if it doesn't match the configured epoch length.

**Comment by joshuahannan** [comment]
@jordanschalm Can you elaborate on this point?

> Enforce sanity check for epoch length input, given the configured DKG phase length and staking auction length, similar to the checks in place for changing configuration

I'm not sure what kind of sanity check is needed

**Comment by joshuahannan** [comment]
@jordanschalm so something like this?
```
endView >= startView + FlowEpoch.configurableMetadata.numViewsInStakingAuction
                           + 3*FlowEpoch.configurableMetadata.numViewsInDKGPhase - (1 as UInt64),
```

**Comment by jordanschalm** [comment]
Exactly, added a suggestion: https://github.com/onflow/flow-core-contracts/pull/186#discussion_r639197662
