### ISSUE TITLE
Validate QC vote submissions in FlowQC Contract

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-core-contracts#181]
## Context

We need to validate QC votes submissions in the QC smart contracts to ensure that only valid votes are included in the `EpochSetup` service event. This is also needed to ensure the smart contract knows when it has met the threshold for constructing a QC. 

## Open Questions

* How do we provide the smart contract with the root QC message digest? (needed to validate votes)
  * We could provide it along with the vote message - but these are untrusted inputs.
  * Ideally the smart contract can compute this value on its own (it has all the data, it is missing the mechanism building/encoding/hashing the root block and root QC objects)
* Should we change input types (is there a `Signature` type with the new crypto API)?
* Can we aggregate the signatures within the smart contract?

**Comment by tarakby** [comment]
The QC in this ticket is only the one used by the collection nodes Hotstuff right?

> is there a Signature type with the new crypto API

No, a signature is just a `[UInt8]`

>Can we aggregate the signatures within the smart contract? 

No. Are we able to survive without this (for now)?

**Comment by jordanschalm** [comment]
> The QC in this ticket is only the one used by the collection nodes Hotstuff right?

👍  Yes

> No. Are we able to survive without this (for now)?

Yes we are fine without aggregation in the contract, we only need vote verification.

**Comment by jordanschalm** [comment]
Closing in favour of https://github.com/dapperlabs/flow-go/issues/5596 so we can track this under the Epoch Ph1 milestone.
