### ISSUE TITLE
BUG: Ability to register nodes with duplicate node IDs

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-core-contracts#222]
### Problem

Nodes are identified by a 32-byte identifier, provided as input by the node operator at the time of registration. In `flow-go` it is represented as a `[32]byte`, in `flow-core-contracts` it is represented as a hex-encoded `String`. 

Node IDs must be unique. The smart contract enforces uniqueness by using the node ID as the key in a dictionary, however this results in uniqueness being defined by the string representation, which means two different operators could input (eg.) `Abcd` and `abcd` and both would be accepted, despite both referring to the same identifier.

### Acceptance Criteria

* Node ID uniqueness should be enforced

**Comment by joshuahannan** [comment]
How can we enforce this in the smart contract, since we take the arguments as strings already?

**Comment by jordanschalm** [comment]
> How can we enforce this in the smart contract, since we take the arguments as strings already?

One way would be to enforce an unambiguous representation, for example requiring all inputs be lowercase or converting them to lowercase.

**Comment by joshuahannan** [comment]
So would I just iterate through each character and make sure it is a number or lowercase hex character?
```
0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f
```

Is there a better way to do it than that?
