### ISSUE TITLE
Update README to have an organized summary, links to correct contracts and docs, and test instructions

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#238]
## Issue To Be Solved

Need to provide better onboarding to this repo for newcomers.
Please tag @joshuahannan here if you'd like some guidance on how to complete this! 😃 

## Suggest A Solution

* Updated summaries of all the contracts
* Links to the correct documentation on the docs site
* Links to the correct transactions
* Instructions for how the Go tests work and how to run them

**Comment by seunbayo** [comment]
@joshuahannan is this still available? any more information?

**Comment by joshuahannan** [comment]
yeah, there are definitely some improvements that could still be made to the readme, like some more details about the contracts, the go packages and how the tests work. How familiar are you with Go and with the smart contracts here? I'm happy to jump on a quick call with you to help you get started and make a plan if you'd like to contribute!

Docs for some of these contracts are here: https://developers.flow.com/concepts/nodes/staking
