### ISSUE TITLE
StakingCollection: Add transaction to restake all staking rewards

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/flow-core-contracts#255]
### Background

A common task for many node operators and delegators is to periodically re-stake their staking rewards. Since the Staking Collection allows for multiple nodes and delegations to be managed by a single account, we should put in place a prescribed transaction that enables a Staking Collection to execute a single transaction which re-stakes all of their staking rewards.

## Further Questions

- Should the "re-stake all" txn re-stake both node operator rewards and delegator rewards, or should there be two re-stake all txns, one for nodes and one for delegations.

### Deliverabless

- [ ] A "re-stake all" transaction(s) exist and associated functionality implemented.

**Comment by joshuahannan** [comment]
Thanks for creating this issue! I'll work on it very soon. 😃
