### ISSUE TITLE
Configurable success threshold in FlowDKG contract

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-core-contracts#260]
## Context

The FlowDKG contract determines whether the DKG process succeeded by observing that the number of agreeing DKG key vector submissions  exceeds some threshold (the safety margin) . Currently that threshold is about 50%, which is the threshold of success for the underlying DKG. 

In the short-term, random beacon keys are required to submit a consensus vote. Therefore the proportion of nodes successfully completing the DKG directly impacts finalization performance. Even <90% completion can significantly degrade finalization. This will be mitigated by signature decoupling in Crypto v2.

To mitigate the problem in the interim we would like to be able to configure the threshold at which FlowDKG contract considers the DKG to have succeeded.

**Target: include this change in Dec 1 Canary spork**

## Definition of Done

* Make the FlowDKG contract support a configurable DKG success safety margin

cc @tarakby

**Comment by tarakby** [comment]
- In order to avoid confusion in the docs and conversations, I suggest to decouple the threshold value `t` (used by the threshold signature and DKG) and the safety rate `r` used by the DKG contract. Currently `r` is set to `t+1` ( note it is not set to `t`). 

- I suggest to keep the definition of `t` in the DKG contract as it is now, and introduce the new value `r`. 
       -  the contract should make the sanity check `n >= r >=  t+1`  ( `r` should not be less than the "native" implementation threshold ). 
       - `r` can be defined as an integer `r = floor (percentage *  n)`  with `n` being the number of nodes and `percentage` a value between 0 and 1 ( I guess fixed for 0.95 for now)

**Comment by joshuahannan** [comment]
@tarakby @jordanschalm Should we allow the admin to change this threshold whenever they want or only when the DKG isn't enabled?

**Comment by jordanschalm** [comment]
I think we should allow changes only when the DKG is not enabled.
