### ISSUE TITLE
Update Core Contracts to be compatible with Stable Cadence

### ISSUE THREAD

**Issue by dsainati1** [onflow/flow-core-contracts#294]
### Problem

https://github.com/onflow/flow-core-contracts/blob/master/contracts/LockedTokens.cdc#L231

The linked code does not behave the way it appears to; the `as?` in this line does not actually function as a reference operator. In a future version of Cadence this code will be rejected by the typechecker. 

### Steps to Reproduce 

Typecheck this contract on the master version of Cadence.

**Comment by joshuahannan** [comment]
I've made a PR to address stable cadence changes: https://github.com/onflow/flow-core-contracts/pull/319

**Comment by turbolent** [comment]
@joshuahannan I guess this is complete and can be closed?

**Comment by joshuahannan** [comment]
yeah
