### ISSUE TITLE
Automated Slot Selection

### ISSUE THREAD

**Issue by Wolog2021** [onflow/flow-core-contracts#311]
### Issue To Be Solved
Implement Slot Selection, which imposes limits on the number of nodes of each type that can be included for staking.

#### Spec
The spec is currently only in notion. This should be updated in the FLIP:
https://www.notion.so/dapperlabs/Automated-Slot-Assignment-848564a75f924b1b91ee146e7316cc65#f40b396861594c83ab73a36918efdc95

**Comment by joshuahannan** [comment]
closing this because we are merging soon
