### ISSUE TITLE
documentation references cdc file doesn't not exist

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-core-contracts#338]
Documentation Question.

This page on dev portal: 
https://developers.flow.com/flow/core-contracts/locked-tokens	

references this transaction that no longer exists in github.  https://github.com/onflow/flow-core-contracts/blob/master/transactions/lockedTokens/admin/create_admin_collection.cdc

**Comment by alilloig** [comment]
@janezpodhostnik @joshuahannan do you know which transaction should be linked there? I took a quick look and can't find a tx that seems to be an admin resource setup

**Comment by janezpodhostnik** [comment]
There it went: https://github.com/onflow/flow-core-contracts/pull/34
Not sure why though.

**Comment by joshuahannan** [comment]
That was removed because it isn't supported after the other upgrade in that PR that Janez linked. We can remove the link to it from the public docs
