### ISSUE TITLE
Underflow in `FlowStorageFees`

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#343]
### Problem

A community member reported getting an underflow error from `FlowStorageFees` while performing a regular token transfer.
Discord thread: https://discord.com/channels/613813861610684416/621847426201944074/1070550046015242270

### Steps to Reproduce 

Not sure how to reproduce, but the flowscan link is here: https://flowscan.org/transaction/99160c9460cb1faea9b693f26c9f5d4f851a5d462e49aaf60355b56e3826c9c3/script

### Acceptance Criteria

Diagnose what is causing the underflow and use a better error message

cc @janezpodhostnik

**Comment by janezpodhostnik** [comment]
Thanks for reporting this. I'll take a look.
