### ISSUE TITLE
Implement FungibleTokenMetadataViews in FlowToken

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-core-contracts#369]
### Issue To Be Solved
[FlowToken](https://github.com/onflow/flow-core-contracts/blob/master/contracts/FlowToken.cdc) needs to be updated with implementation of [FungibleTokenMetadataViews](https://github.com/onflow/flow-ft/blob/master/contracts/FungibleTokenMetadataViews.cdc) introduced in [FLIP 1087](https://github.com/onflow/flips/blob/main/application/20220811-fungible-tokens-metadata.md)

Given the support for metadata, we may also consider implementing [ViewResolver](https://github.com/onflow/flow-nft/blob/master/contracts/ViewResolver.cdc), though that's an optional consideration.

### Suggest A Solution
Vaults should implement `MetadataViews.Resolver` and resolve `FTView`, `FTDisplay`, and `FTVaultData`.

If it's decided that FlowToken implements `ViewResolver`, then the relevant contract methods should also be added and resolve `FTVaultData`.

**Comment by sisyphusSmiling** [comment]
@joshuahannan I can get this done if you have other work to complete. I l likely wouldn't get to it until next week as Hybrid Custody audit response and ETH Waterloo will have my attention this week

**Comment by joshuahannan** [comment]
I'm gonna work on this this week @sisyphusSmiling so no need for you to do it. Thanks for offering though!
