### ISSUE TITLE
Port a the SoR History fix to Stable Cadence

### ISSUE THREAD

**Issue by tarakby** [onflow/flow-core-contracts#421]
### Issue To Be Solved
Port https://github.com/onflow/flow-core-contracts/pull/416 to https://github.com/onflow/flow-core-contracts/tree/stable-cadence

**Comment by joshuahannan** [comment]
Completed in [1b20b4d](https://github.com/onflow/flow-core-contracts/pull/319/commits/1b20b4de9450133137b58f8c6bf8078a8e4636bb)
