### ISSUE TITLE
Use semantic versioning and tags

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-core-contracts#424]
### Problem

ATM this repo is not tagged when used in things like flowkit

### Steps to Reproduce 

Nothing
### Acceptance Criteria

When this repo is used in a tagged version of upstream code it should use a tag from this repo  
### Context

Working on dependent code that is not updated correctly because commit versions are used and not tags.

**Comment by peterargue** [comment]
before/while we're at it, let's also tag a new version for https://github.com/onflow/flow-ft

and update this import to use the tag:
https://github.com/onflow/flow-core-contracts/blob/272df6c01e8fa09ab772466ef508dc8ac3045d7e/lib/go/contracts/go.mod#L7

**Comment by joshuahannan** [comment]
I tagged new versions for flow-nft and flow-ft after merging the feature branches. I'm working on getting the tests passing here after upgrading the dependencies, and then I'll do a release here.

**Comment by joshuahannan** [comment]
I just published the new releases for `flow-core-contracts`

* [contracts](https://github.com/onflow/flow-core-contracts/releases/tag/lib%2Fgo%2Fcontracts%2Fv1.0.0)
* [templates](https://github.com/onflow/flow-core-contracts/releases/tag/lib%2Fgo%2Ftemplates%2Fv1.0.0)
