### ISSUE TITLE
Staking Helper Contract

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#5]
Need to design and code a first draft of the staking helper contract

Requirements are outlined in this doc: https://www.notion.so/dapperlabs/Token-Staking-Process-6877e85a057e4eab8beae7f5187f3ffb

## Completion Criteria

- [ ] Conversation with Max, Josh, Layne, and Peter about staking helper requirements
- [ ] Clear high-level documentation in the notion document
- [ ] Updated flow chart
- [ ] First draft of staking helper contract that aligns with the design document

**Comment by caseyturnerarrington** [comment]
We decided to go a different direction with the implementation of this contract. Closing this ticket
