### ISSUE TITLE
Add getDelegatorNodeID function to LockedTokens contract

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-core-contracts#60]
### Issue To Be Solved

Currently the `LockedTokens.LockedAccountInfo` interface includes these methods:
- `getNodeID` - node ID of a staked node
- `getDelegatorID` - delegator ID 

However, in order to fetch delegator info from the central staking contract, we need both the delegator ID and the node ID being delegated to. The currently implementation doesn't provide the node ID that is being delegated to.

### Suggest A Solution

Add a `getDelegatorNodeID` function to the `LockedTokens.LockedAccountInfo` interface

### Context

This is currently blocking @JeffreyDoyle from testing delegation through Flow Port

**Comment by joshuahannan** [comment]
closing because this is complete
