### ISSUE TITLE
Staking: Delegation Contract

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#7]
Need a service account smart contract to manage delegation and enforce rules for node operators.

Details are in https://www.notion.so/dapperlabs/Flow-Delegation-a39af01f4ccc4ce3abaf7614679b3824

**Comment by laynelafrance** [comment]
@joshuahannan do we have a ticket for the locked tokens contract or should we update this one?

**Comment by joshuahannan** [comment]
This one can be moved to Done and I'll create another issue for locked tokens
