### ISSUE TITLE
Improvements to Staking and Locked Tokens

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#84]
### Issue To Be Solved
There are various improvements we could make to the staking and locked tokens contracts. This is to track those.

### Suggest A Solution

* Add a total committed stake to NodeInfo object
* Add total tokens overall to NodeInfo object
* Add cancel unstaking request functionality
* Add a public interface to show an account’s node info

**Comment by laynelafrance** [comment]
@joshuahannan is it ok if I put the contract upgrades to better support epoch contracts in this epic? (Pasting notes below but we can move when we know where to action - To Be Discussed in Grooming later today)

## Context 
Upgrading staking contract will block epoch contracts 

NOTE: 
- This is a serious action that could erode trust if we aren't thoughtful
- We need to figure out how to make this change without upgrading state for users in a way they dont expect
    - **Reference Solution:** Erlang would allow for this - they're designed to be upgraded while they're executing. Stateful mechanisms act like resources and can upgrade internal state while executing.

## Definition of Done 
- Contract Changes:
    - 2/3 sprints + (includes staking and locked token changes)
- Migration overhead:
    - Depends on user action we're willing to tolerate
    - Re-using existing secondary account and then migrating ledger only likely easiest
    - UNKNOWNS:
        - Migration versus moving state options
        - 0.5-1 sprint planning + 1-2 sprints work
- Locked Tokens could also be re-architected 
          - Contract changes:
               - Must - but not significant changes
          - Feasible?
          - Cost/Benefit

**Comment by joshuahannan** [comment]
Closing this because the work in it has been completed
